name: Azure CI/CD - Medical Chatbot

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  ACR_NAME: hydermedicalacr
  IMAGE_NAME: medicalbot

jobs:

  Continuous-Integration:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show project files
        run: |
          pwd
          ls -la
          echo "----- Dockerfile -----"
          cat Dockerfile
          echo "----- Git commit -----"
          git rev-parse HEAD

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check Azure and ACR
        run: |
          echo "ACR_NAME=$ACR_NAME"
          az account set --subscription "634cd74f-3c11-4cfe-afde-4c0c8b1bd122"
          az account show --query "{subscription:id,tenant:tenantId}" -o table
          az acr show --name $ACR_NAME --resource-group Hyder --query "{name:name,loginServer:loginServer,location:location,sku:sku.name}" -o table

      - name: Login to Azure Container Registry
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker image
        run: |
          docker build \
            -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} \
            -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest \
            .

      - name: Push Docker image
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Show pushed images
        run: |
          echo "Image pushed successfully:"
          echo "$ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}"
          echo "$ACR_NAME.azurecr.io/$IMAGE_NAME:latest"